name: CI
on: [push]
jobs:
  build-on-unix:
    strategy:
      matrix:
        java: [8,11]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} java ${{ matrix.java }}
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.maven
          key: maven-${{ matrix.os }}-maven-cache
          restore-keys: |
            ${{ matrix.os }}-maven-cache-
      - name: Test maven app
        shell: bash
        run: |
          ./mvnw
          ./mvnw
  build-on-windows:
    strategy:
      matrix:
        java: [11,1.8]
        nodejs-version: [12]
        maven-version: [6.3]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} java ${{ matrix.java }}
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.maven
          key: ${{ runner.os }}-${{ matrix.os }}-maven-${{ hashFiles('**/*.pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os }}-maven-
      - name: Test maven app
        shell: cmd
        run: |
          @chcp 65001>nul
          call mvnw
          call mvnw
